RN	ENTRADAS							SAIDA
Numero	Idade	Pressão	KdComida	BatimentoCardiaco	Glicemia	TaxaHormonal	Sedentario	Chance Diabetico
1	JOVEM	ALTA	MUITO	ALTO	ALTA	ALTA	NAO	TEM
2	JOVEM	NORMAL	MUITO	ALTO	NORMAL	ALTA	SIM	TEM
3	JOVEM	BAIXA	MUITO	ALTO	BAIXO	NORMAL	NAO	NAO TEM
4	JOVEM	ALTA	POUCO	NORMAL	NORMAL	NORMAL	SIM	NAO TEM
5	JOVEM	NORMAL	POUCO	NORMAL	ALTA	BAIXA	NAO	NAO TEM
6	JOVEM	BAIXA	POUCO	NORMAL	BAIXO	BAIXA	SIM	TEM
7	JOVEM	ALTA	MUITO	BAIXO	ALTA	ALTA	NAO	TEM
8	JOVEM	NORMAL	MUITO	BAIXO	NORMAL	ALTA	SIM	NAO TEM
9	JOVEM	BAIXA	MUITO	BAIXO	BAIXO	NORMAL	NAO	NAO TEM
10	JOVEM	ALTA	POUCO	ALTO	ALTA	NORMAL	SIM	TEM
11	ADULTO	ALTA	POUCO	ALTO	ALTA	ALTA	NAO	TEM
12	ADULTO	NORMAL	MUITO	NORMAL	ALTA	NORMAL	SIM	NAO TEM
13	ADULTO	BAIXA	POUCO	ALTO	ALTA	BAIXA	SIM	TEM
14	ADULTO	ALTA	MUITO	NORMAL	NORMAL	ALTA	NAO	NAO TEM
15	ADULTO	NORMAL	POUCO	ALTO	NORMAL	NORMAL	NAO	TEM
16	ADULTO	BAIXA	MUITO	NORMAL	NORMAL	BAIXA	NAO	TEM
17	ADULTO	ALTA	POUCO	BAIXO	BAIXO	ALTA	SIM	NAO TEM
18	ADULTO	NORMAL	MUITO	BAIXO	BAIXO	NORMAL	SIM	NAO TEM
19	ADULTO	BAIXA	POUCO	BAIXO	BAIXO	BAIXA	NAO	TEM
20	ADULTO	NORMAL	MUITO	NORMAL	BAIXO	ALTA	SIM	NAO TEM
21	IDOSO	ALTA	POUCO	ALTO	BAIXO	ALTA	SIM	TEM
22	IDOSO	NORMAL	MUITO	BAIXO	ALTO	ALTA	NAO	TEM
23	IDOSO	BAIXA	MUITO	NORMAL	NORMAL	ALTA	SIM	NAO TEM
24	IDOSO	ALTA	MUITO	BAIXO	BAIXO	NORMAL	SIM	NAO TEM
25	IDOSO	NORMAL	POUCO	ALTO	ALTO	NORMAL	NAO	TEM
26	IDOSO	BAIXA	POUCO 	BAIXO	NORMAL	NORMAL	SIM	NAO TEM
27	IDOSO	ALTA	POUCO 	NORMAL	BAIXO	BAIXA	NAO	NAO TEM
28	IDOSO	NORMAL	POUCO	NORMAL	ALTO	BAIXA	SIM	TEM
29	IDOSO	BAIXA	POUCO	ALTO	NORMAL	BAIXA	NAO	NAO TEM
30	IDOSO	ALTA	MUITO	ALTO	NORMAL	BAIXA	NAO	TEM